image: node:latest

stages:
  - init
  - lint
  - test

build_backend:
  stage: init
  script:
    - cd backend && npm install
  artifacts:
    paths:
      - backend

build_frontend:
  stage: init
  script:
    - cd frontend && npm install
  artifacts:
    paths:
      - frontend

lint_backend:
  stage: lint
  script:
    - cd backend && npm run lint
  dependencies:
    - build_backend

lint_frontend:
  stage: lint
  script:
    - cd frontend && npm run lint
  dependencies:
    - build_frontend

